name: CI

on:
  push:
    branches: [ master ] 
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        ols_version: [1.7.13, 1.6.21]
        php_version: [lsphp74, lsphp73, lsphp72]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
         username: heremoryoo
         password: ${{ secrets.DOCKER_TOKEN }}
         logout: true

      - name: Build Images
        env:
          OLS_VERSION: ${{ matrix.ols_version }}
          PHP_VERSION: ${{ matrix.php_version }}
        run: |
          cd template && ./build.sh --ols $OLS_VERSION --php $PHP_VERSION
